import {authenticatedFetch} from './supabase';
import {useEffect,useMemo,useRef,useState} from 'react';
import {AudioBufferQueue,joinPassages,speechChunks,audioError} from './audio';
export default function Narrator({blocks,paid}:{blocks:string[];paid:boolean}){
 const [mode,setMode]=useState('browser'),[speaker,setSpeaker]=useState('athena'),[speed,setSpeed]=useState(1),[status,setStatus]=useState('idle'),[position,setPosition]=useState(0),[error,setError]=useState('');
 const queue=useRef<AudioBufferQueue|null>(null),player=useRef<HTMLAudioElement|null>(null),url=useRef<string|null>(null),generation=useRef(0);
 const units=useMemo(()=>joinPassages(blocks.flatMap((text,blockIndex)=>speechChunks(text).map(text=>({text,blockIndex,paragraphEnd:true})))),[blocks]);
 function stop(){generation.current++;queue.current?.stop();player.current?.pause();window.speechSynthesis?.cancel();if(url.current)URL.revokeObjectURL(url.current);url.current=null;setStatus('idle')}
 useEffect(()=>{stop();setPosition(0);return stop},[units]);
 async function start(at=position){stop();setError('');const token=++generation.current;if(!units[at])return;
  if(mode==='browser'){
   if(!window.speechSynthesis){setError('Device narration is unavailable in this browser.');return}
   const play=(i:number)=>{if(token!==generation.current)return;if(!units[i]){setStatus('idle');return}setPosition(i);const speech=new SpeechSynthesisUtterance(units[i].text);speech.rate=speed;speech.lang='en';const voices=window.speechSynthesis.getVoices().filter(v=>v.lang.startsWith('en'));speech.voice=voices.find(v=>/natural|neural|online/i.test(v.name))||voices[0]||null;speech.onstart=()=>setStatus('playing');speech.onend=()=>play(i+1);speech.onerror=()=>setStatus('idle');window.speechSynthesis.speak(speech)};play(at);return;
  }
  const buffer=new AudioBufferQueue(async(i,signal)=>{const r=await authenticatedFetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:units[i].text,speaker}),signal:AbortSignal.any([signal,AbortSignal.timeout(45000)])});if(!r.ok){const d=await r.json() as {error?:string};throw new Error(d.error||`Voice failed (${r.status})`)}if(!r.headers.get('content-type')?.startsWith('audio/'))throw new Error('Invalid voice response');return r.blob()},units.length);queue.current=buffer;const audio=new Audio();player.current=audio;
  const fail=(e:unknown)=>{if(token===generation.current){stop();setError(audioError(e))}};
  const play=async(i:number):Promise<void>=>{if(token!==generation.current)return;if(!units[i]){setStatus('idle');return}setStatus('loading');setPosition(i);const blob=await buffer.take(i);if(token!==generation.current)return;url.current=URL.createObjectURL(blob);audio.src=url.current;audio.playbackRate=speed;audio.onplaying=()=>setStatus('playing');audio.onended=()=>{if(url.current)URL.revokeObjectURL(url.current);url.current=null;void play(i+1).catch(fail)};audio.onerror=()=>fail(new Error('Audio could not be decoded.'));await audio.play()};void play(at).catch(fail);
 }
 function toggle(){if(status==='playing'){mode==='ai'?player.current?.pause():window.speechSynthesis.pause();setStatus('paused')}else if(status==='paused'){if(mode==='ai')void player.current?.play().catch(e=>{setError(audioError(e));setStatus('idle')});else window.speechSynthesis.resume();setStatus('playing')}else void start()}
 return <section className="narrator" aria-label="Narration"><div className="row"><span className="sound">◖))</span><strong>Listen to this book</strong><span className="muted">Passage {position+1} / {units.length}</span></div><div className="row wrap"><button onClick={toggle} disabled={!units.length||status==='loading'}>{status==='playing'?'Pause':status==='paused'?'Resume':status==='loading'?'Preparing audio…':'▶ Listen'}</button><button className="ghost" onClick={stop}>Stop</button><label>Voice mode<select value={mode} onChange={e=>{stop();setMode(e.target.value)}}><option value="browser">Device voice · Free</option><option value="ai" disabled={!paid}>Aura-2 · Paid</option></select></label>{mode==='ai'&&<label>Speaker<select value={speaker} onChange={e=>{stop();setSpeaker(e.target.value)}}>{['athena','pluto','orpheus','pandora','vesta','minerva','zeus','orion'].map(s=><option key={s}>{s}</option>)}</select></label>}<label>Speed<select value={speed} onChange={e=>{stop();setSpeed(Number(e.target.value))}}>{[.8,1,1.15,1.3].map(v=><option key={v} value={v}>{v}×</option>)}</select></label></div>{mode==='ai'&&<small>The current and next passage are sent to Cloudflare for narration and count toward your allowance.</small>}{error&&<p role="alert" className="error">{error}</p>}</section>
}
